services:
  - type: web
    name: truth-likelihood-server
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r ml-model/requirements.txt && cd server && npm install && cd ..
    startCommand: cd server && npm start
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
